### PR TITLE
Small refactoring of the new table view PHP code

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
This splits methods, removes not needed code and improves type inferrence.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
I have not tested this as I have no working MW install at the moment :)

**Comment by gesinn-it** [comment]
Thanks @JeroenDeDauw for having a look at this. I'll update my test instance and check if everything is working.

**Comment by gesinn-it** [comment]
@JeroenDeDauw , I had a look at you changes. It seems that there are issues with your changes as the table now does not show headers anymore. And in my test case it shows two empty columns at the end of the table.

**Comment by JeroenDeDauw** [comment]
Ah... this is really no sane way to work on something :)

Thanks for doing the effort of posting a screenshot. I've now amended this PR, so that `getTableHeader` actually returns its result :)

**Comment by gesinn-it** [comment]
@JeroenDeDauw what shall we do next? I'll not merge your pull request for the moment, right?

**Comment by JeroenDeDauw** [comment]
If I fixed the issues you observed and you have no objections to these changes being made to the format you added, then please merge.

**Pull request merged**
